### ISSUE TITLE
Why it is not possible to send BLE advertisement on channels other than 37, 38, 39?  

### ISSUE THREAD

**Issue by kainataltaf** [spoerk/contiki#13]
Why it is not possible to send BLE advertisement on channels other than 37,38,39? Is it a radio level limitation?
I have gone through the internet links as well but everyone mentioned: You can send advertisements on these three channels, without giving reason where and why is this limitation?
My goal is to send and receive BLE Advertisements but due to other BLE advertisements traffic on these channels my packet receive on very low rate.

**Comment by spoerk** [comment]
Hi, this is a limitation of the BLE specification, which specifies that advertisements are only sent on channels 37-39 (at least for BLE devices with a version of below 5.0).
In BLE 5 and above, there is the possibility so send extended advertisement packets, which may be sent on any of the 40 possible BLE channels.
