### ISSUE TITLE
cc26xx-ble-client-demo - doesn't turn on

### ISSUE THREAD

**Issue by sheetalsingala** [spoerk/contiki#3]
When I flash the CC2650 with the cc26xx-ble-client-demo and it stops working. It doesnt turn on.
If I flash it with any of the other files,it works.

**Comment by spoerk** [comment]
Can you please give more information on your setup and your problem?
Do you use a TI CC2650 SensorTag or a Launchpad?
What do you mean with it stops working (does it reboot, do you see any serial output)?
