### ISSUE TITLE
Timing issue with different PHY settings in BLE5

### ISSUE THREAD

**Issue by onefreebjy** [spoerk/contiki#5]
Hi, I'm working on the new Bluetooth 5 radio with launchpad CC2640R2 recently. By altering the PHY setting from default 1 Mbps to 2 Mbps, (coded) 500 kbps, and 125 kbps, the master & slave commands could no longer proceed correctly and prompted with error code 0x1402 - NOSYNC.  There must be some timing problems during connection event. Any thoughts about it?

**Comment by spoerk** [comment]
This indeed sounds like a timing problem of the individual connection events (master and slave commands). Is this problem still persisting?
