### ISSUE TITLE
Packet receive interrupt from rf core is invalid?

### ISSUE THREAD

**Issue by howard1985** [spoerk/contiki#6]
In ble-hal-cc26xx.c  line 1153, RX_ENTRY_STATUS(param->rx_queue_current) == DATA_ENTRY_FINISHED), How does Cortex M3  get packet from cortex M0?
 Where  is rx_queue_current set to be DATA_ENTRY_FINISHED?
I have done a test, uncommon line 441 code  rf_core_setup_interrupts(0); the ble also connect success.
why? thanks!

**Comment by desword** [comment]
Can you tell me how to connect the ble?
https://github.com/spoerk/contiki/issues/8

**Comment by howard1985** [comment]
Well, contiki-ng has already connected one sensortag with the other one, so I can say it completed the GAP  and the connect event  process. But it is just part of link layer protocol,  and if you want to connnet with smartphone through ble, you also have to add  ATT and GATT.
      I have written part of GATT and ATT according to the control package and message package comand that is receied in link layer, of course the ble protocol is important, but it is enough to connect ble, and can communication with each other. But the connect event is not sync with smartphone for long time, I think the root of problem is SCA, so I want to know why the interrupt of receive connect event can not happen in CC2650 while 15.4 could do.


| |
燕元超
|
|
dafuwong@163.com
|
签名由网易邮箱大师定制
On 1/5/2019 15:56，desword<notifications@github.com> wrote：

Can you tell me how to connect the ble?
#8

**Comment by desword** [comment]
Thanks very much for your answer, but it seems a mistake that I provide a wrong question. 
The whole question is actually in https://github.com/spoerk/contiki/issues/8.

Sepcifically, I don't know how to set the PEER_ADDRESS and server ip to make the two examples work.

**Comment by howard1985** [comment]
Oh, I am sorry too, I thought you want to connect smartphone, and did not saw #8.
My friend had done the test  between two board. According to the code, just try it like this.
client.c
#define SERVER_IP"fe80::Ce78:ABff:fe3A:2901"
project_conf.h
#define BLE_MODE_CONF_INIT_PEER_ADDR      0xCC78AB3A2881


| |
燕元超
|
|
dafuwong@163.com
|
签名由网易邮箱大师定制
On 1/5/2019 18:38，desword<notifications@github.com> wrote：

Thanks very much for your answer, but it seems a mistake that I provide a wrong question.
The whole question is actually in #8.

Sepcifically, I don't know how to set the PEER_ADDRESS and server ip to make the two examples work.

**Comment by spoerk** [comment]
It seems odd that you still receive packets, even when you disable the RF core interrupts.
Are you sure that the interrupts are completely disabled?
