### ISSUE TITLE
how to set the PEER_ADDRESS and server ip to make the example work?

### ISSUE THREAD

**Issue by desword** [spoerk/contiki#8]
Hello, I stuck at the two ble-demo.
I can successfully compile the two example, however, I can not make them create connections. 

In the client.c. I modify the SERVER_IP as 
```
#define SERVER_IP               "fe80::1"
```

In the server demo of the project-conf.h, I am confused with the `BLE_MODE_CONF_INIT_PEER_ADDR` and don't know  how to set it. Currently, I set it as:
```
// #define BLE_MODE_CONF_INIT_PEER_ADDR      0x2471891A2A82
#define BLE_MODE_CONF_INIT_PEER_ADDR      0x822A1A897124
```
Which is the client MAC address. I saw it on my phone.

With the above settings, it can not work.
Anyone can give some hints? Thanks!

**Comment by spoerk** [comment]
Does the BLE central (server) successfully detect the BLE peripheral (client)? If so, does the connection between the two devices successfully get established?

**Comment by desword** [comment]
The problem has been solved. Just as the https://github.com/spoerk/contiki/issues/6#issuecomment-451808427 said, by successfully setting the PEER_ADDRESS and server ip.

In summary, the SERVERP IPv6 in the client.c should be calculated through MAC address. 

For the PEER_ADDRESS in the server project-conf.h, we can read the client MAC address using TI programmer.

**Comment by kainataltaf** [comment]
I am facing the same issue.
I have set the PEER_ADDRESS as 0xB09122EA7586 which is mac address of my client in server project configuration file.
How to find Server IP? I am still clueless.
